name: Lint Code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install ESLint
        run: npm install eslint --global

      - name: Run Linter
        run: |
          # This command finds all JavaScript files recursively and runs ESLint on them
          eslint ./server/database --env browser --env es2021 --env node --parser-options '{"ecmaVersion": 12}' --rule '{"no-unused-vars": "warn", "semi": ["error", "always"]}'
          echo "Linted all the JavaScript files successfully"
